/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package td5;

public class App {

    public static void main(String[] args) {
        Unité u1 = new Unité();
        u1.setAttaqueStrategy(new Canon());
        u1.setDéplacementStrategy(new Rouler());
        u1.combattre();
        u1.seDéplacer();
    }
}
